version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: rinha-db-2025
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_DB=rinha
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rinha -d rinha" ]
      interval: 5s
      timeout: 5s
      retries: 5
    # ----------------------------------------
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "80MB"
    networks:
      - rinha-net

  api01: &api
    build: .
    hostname: api01
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "135MB"
    networks:
      - rinha-net
      - payment-processor
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/rinha
      - healthcheck.scheduler.enabled=true

  api02:
    <<: *api
    hostname: api02
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/rinha
      - healthcheck.scheduler.enabled=false

  nginx:
    image: nginx:1.25.2-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "10MB"
    networks:
      - rinha-net

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true
    name: payment-processor